#
# Copyright (c) 2019-2020 P3TERX <https://p3terx.com>
#
# This is free software, licensed under the MIT License.
# See /LICENSE for more information.
#
# https://github.com/P3TERX/Actions-OpenWrt
# Description: Build OpenWrt using GitHub Actions
#

name: Build OpenWrt

on:
  push:
    branches:
      - master
      - feat/cncd-customization

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      id: checkout
      uses: actions/checkout@v3

    - name: Install necessary software
      id: builder_provisioning
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo rm -rf /etc/apt/sources.list.d/* /usr/share/dotnet /usr/local/lib/android /opt/ghc || true
        sudo -E apt-get -qq update
        sudo -E apt-get -qq install build-essential clang flex g++ gawk gcc-multilib gettext git libncurses5-dev libssl-dev python3-distutils rsync unzip zlib1g-dev file wget python2
        sudo -E apt-get -qq autoremove --purge
        sudo -E apt-get -qq clean
    
    - name: Setup Rust
      id: setup_rust
      run: |
        curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
        source $HOME/.cargo/env
        rustup target add mipsel-unknown-linux-musl
        df -hT $PWD


    - name: Update feeds
      id: feeds_update
      run: |
        ./scripts/feeds update packages
    
    - name: Install feeds
      id: feeds_install
      run: |
        ./scripts/feeds install libpam libgnutls libopenldap libidn2 libssh2 libcap liblzma libnetsnmp jansson

    - name: Download packages
      id: download
      run: |
        make defconfig
        make download -j$(nproc)

    - name: Compile the firmware
      id: build
      run: |
        source $HOME/.cargo/env
        make -j$(nproc) world        

    - name: Archive production artifacts
      uses: actions/upload-artifact@v3
      with:
        name: firmware
        path: |
          bin/**/*.bin

    - name: Delete workflow runs
      uses: GitRML/delete-workflow-runs@main
      with:
        retain_days: 1
        keep_minimum_runs: 3
